### ISSUE TITLE
Donation and subscription

### ISSUE THREAD

**Issue by singh-sahib-india** [Kry9toN/Kry9toN.github.io#1]
I donated and subscribed for adfree experience for TB Checker but developer isn't responding on play store

**Comment by Kry9toN** [comment]
can you contac me on email?

**Comment by singh-sahib-india** [comment]
I sent you email from my purchasing play store account "iwouldlike2hear" Please check,thanks

**Comment by singh-sahib-india** [comment]
I also sent you messages on telegram "Kry9toN" please check

**Comment by singh-sahib-india** [comment]
I am still seeing ads in whole sale even I donated to support development
